# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b2c54b5b-11fe-4844-bf77-9beac147ecf8";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/04dcf815-3915-4534-8166-47188f656117"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  boot.loader.grub.enable = true;
  boot.loader.grub.device = "/dev/sda";
  boot.loader.grub.useOSProber = true;

  boot.loader.grub.enableCryptodisk=true;

  boot.initrd.luks.devices."luks-0175ab46-61aa-4a54-9283-333f2df2d2b7".device = "/dev/disk/by-uuid/0175ab46-61aa-4a54-9283-333f2df2d2b7";
  boot.initrd.luks.devices."luks-d12f3ea8-497a-4afc-b3b1-036352a3cbff".device = "/dev/disk/by-uuid/d12f3ea8-497a-4afc-b3b1-036352a3cbff";

  boot.initrd.secrets = {
    "/crypto_keyfile.bin" = null;
  };

  boot.initrd.luks.devices."luks-0175ab46-61aa-4a54-9283-333f2df2d2b7".keyFile = "/crypto_keyfile.bin";
  boot.initrd.luks.devices."luks-d12f3ea8-497a-4afc-b3b1-036352a3cbff".keyFile = "/crypto_keyfile.bin";
}
